baseURL = 'https://fengyao321.github.io/'
languageCode = 'zh-cn'
title = "Yao"
theme = "yinyang"

[params]
  description = "保持好奇，记录思考。"
  headTitle = "Yao"
  mainSections = ["posts"]

[params.author]
  name = "Yao"

[[params.socials]]
  name = "About"
  link = "https://github.com/fengyao321"

[[params.socials]]
  name = "RSS"
  link = "/index.xml"
