baseURL = 'https://fengyao321.github.io/'
languageCode = 'zh-cn'
title = "Yao"
theme = "nostyleplease"

[params]
  description = ""
  author = "fengyao"
  bio = ""
  avatar = "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&h=256&q=80"
  mainSections = ["posts"]

  [params.theme_config]
    appearance        = "auto"
    back_home_text    = ".."
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true
    show_description  = true
